version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Exposing Vite's default port
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8080  # Example env var for API calls

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
